### ISSUE TITLE
Exception while installing the "uAAL-Basic.Coordinator" feature

### ISSUE THREAD

**Issue by steveStavros** [universAAL/ui#4]
Hi all,

I am trying to set uAAL in a Raspeberry pi device. I downloaded the karaf distribution of uAAL ( https://github.com/universAAL/distro.karaf) and then I used the starting guide (https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide) and tried to install the "uAAL-Basic.Coordinator" feature, as it is recommended, but I get the following error:

Error executing command: Can't install feature uAAL-Basic.Coordinator/0.0.0: 	
Could not start bundle mvn:org.universAAL.ui/ui.resource.server/3.4.1-SNAPSHOT in feature(s) uAAL-UI.resource.server-3.4.1-SNAPSHOT: Unresolved constraint in bundle ui.resource.server [135]: Unable to resolve 135.0: missing requirement [135.0] osgi.wiring.package; (&(osgi.wiring.package=org.universAAL.middleware.container.osgi.util)(version>=3.4.0)(!(version>=4.0.0)))

**Comment by amedranogil** [comment]
moved to https://github.com/universAAL/platform/issues/12
